platform:
  - amd64
image: Visual Studio 2015

services:
  - mongodb

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"

## For debugging uncomment the lines below
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # export BRANCH environment variable to have unified names across different CI services
  - "SET BRANCH=%APPVEYOR_REPO_BRANCH%"
  # the CONDA_SUFFIX is used to distinguish main and dev builds
  - IF "%$BRANCH%"=="master" (SET CONDA_SUFFIX="")
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels tpeulen
  - conda config --add channels salilab
  - conda create -n build python=3.7 git conda-build anaconda-client conda-verify ripgrep
  - activate build
  - git submodule update --init --force
  - if not "%$BRANCH%" == "master" (SET CONDA_SUFFIX="") else (SET CONDA_SUFFIX="dev")
  - conda build conda-recipe

# to run your custom scripts instead of automatic tests
test_script:
  - conda install chinet nose coverage numba -c local
  - cmd: echo %CD%
  - cmd: cd C:\projects\chinet\test\
  - cmd: echo %CD%
  - nosetests
  - cd ..

### scripts to run after tests
deploy_script:
  - if not "%APPVEYOR_REPO_BRANCH%" == "master" (SET ANACONDA_LABEL="nightly") else (SET ANACONDA_LABEL="main")
  - anaconda -t %ANACONDA_API_TOKEN% upload -u %CONDA_USER% -l %ANACONDA_LABEL% bld-dir/win-64/*.tar.bz2 --force

build: off

## For debugging uncomment the lines below
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
  - provider: Email
    to:
      - thomas.otavio.peulen@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
