stages:
- build
- test
- deploy
- Trigger-cross-projects

build:linux:
  stage: build
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential doxygen git
  script:
    - git clone https://gitlab.peulen.xyz/build/conda_config
    - ./conda_config/setup.sh
    - ./conda_config/build.sh
  artifacts:
    paths:
      - bld-dir/

build:windows:
  stage: build  
  tags:
    - win
  script:
    - git clone https://gitlab.peulen.xyz/build/conda_config
    - .\conda_config\setup.bat
    - .\conda_config\build.bat
  artifacts:
    paths:
      - bld-dir/

build:osx:
  stage: build
  tags:
    - osx
  script:
    - git clone https://gitlab.peulen.xyz/build/conda_config
    - ./conda_config/setup.sh
    - ./conda_config/build.sh
  artifacts:
    paths:
      - bld-dir/

test:linux:
  stage: test
  tags:
    - linux
  image: condaforge/mambaforge:latest
  dependencies:
    - build:linux
  script:
    # for libmongoc
    - conda config --add channels tpeulen
    # for chinet
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install -y python=3.7 chinet mongodb nose numba
    - mkdir db & nohup mongod --dbpath db &
    - cd test
    - nosetests
    - pkill mongodb

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge:latest
  tags:
    - linux
  dependencies:
    - test:linux
    - build:windows
    - build:osx
  script:
    - git clone https://gitlab.peulen.xyz/build/conda_config
    - ./conda_config/deploy.sh

# Downstream projects
chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf

