stages:
- build
- test
- deploy
- Trigger-cross-projects

.BuildTemplate: &build_template
  artifacts:
    paths:
      - bld-dir/
.WinTemplate:  &win_template
  << : *build_template
  image: mambaforge:vs16
  tags:
    - win
  script:
    - cmd.exe
    - conda activate base
    - cd tools && git pull --force && cd..
    - .\tools\build.bat
  before_script:
    - git submodule update --init --recursive --remote
.OSXTemplate:  &osx_template
  << : *build_template
  tags:
    - osx
  before_script:
    - brew reinstall wget git git-lfs
    - git submodule update --init --recursive --remote
.LinuxTemplate:  &linux_template
  << : *build_template
  tags:
    - linux
    - x86_64
  image:
    name: condaforge/mambaforge
    entrypoint: [ "/bin/bash", "-i", "-c" ]
  before_script:
    - apt update
    - apt install build-essential
    - source "/opt/conda/etc/profile.d/conda.sh"
    - conda activate /opt/conda/
    - git submodule update --init --recursive --remote

build:linux:
  << : *linux_template
  stage: build
  script:
    - ./tools/build.sh
build:windows:
  << : *win_template
  stage: build  
  script:
    - .\tools\build.bat
build:osx:
  << : *osx_template
  stage: build
  script:
    - ./tools/build.sh

test:linux:
  stage: test
  <<: *linux_template
  dependencies:
    - build:linux
  script:
    # for librttr
    - conda config --add channels tpeulen
    # for chinet
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install -y chinet mongodb nose numba
    - mkdir db & nohup mongod --dbpath db &
    - cd test
    - nosetests

deploy:conda:
  <<: *linux_template
  stage: deploy
  dependencies:
    - test:linux
    - build:windows
    - build:osx
  script:
    - ./tools/deploy.sh

# Downstream projects
chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf

