stages:
- build
- test
- deploy
- Trigger-cross-projects

.WinTemplate:  &win_template
  tags:
    - win
.OSXTemplate:  &osx_template
  tags:
    - osx
  before_script:
    - brew install wget git git-lfs
.LinuxTemplate:  &linux_template
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential procps wget git git-lfs libglu1-mesa-dev freeglut3-dev mesa-common-dev libusb-dev
.BuildTemplate: &build_template
  before_script:
    - git submodule update --init --recursive --remote
  artifacts:
    paths:
      - bld-dir/

build:linux:
  << : [*build_template, *linux_template]
  stage: build
  script:
    - ./tools/build.sh

build:windows:
  <<: [*build_template, *win_template]
  stage: build  
  script:
    - .\tools\build.bat

build:osx:
  <<: [*build_template, *osx_template]
  stage: build
  script:
    - ./tools/build.sh

test:linux:
  stage: test
  <<: *linux_template
  dependencies:
    - build:linux
  script:
    # for libmongoc
    - conda config --add channels tpeulen
    # for chinet
    - conda config --add channels "file://`pwd`/bld-dir"
    - mamba install -y python=3.8 chinet mongodb nose numba
    - mkdir db & nohup mongod --dbpath db &
    - cd test
    - nosetests

deploy:conda:
  <<: *linux_template
  stage: deploy
  dependencies:
    - test:linux
    - build:windows
    - build:osx
  script:
    - ./tools/deploy.sh

# Downstream projects
chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf

