stages:
- build
- test
- deploy
- Trigger-cross-projects

build:linux:
  stage: build
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential doxygen
  script:
    - conda config --add channels tpeulen
    - mamba install -y boa
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    paths:
      - bld-dir/

build:windows:
  stage: build  
  tags:
    - win
  script:
    - conda config --add channels tpeulen
    - mamba install -y boa
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    paths:
      - bld-dir/

build:osx:
  stage: build
  tags:
    - osx
  script:
    - conda config --add channels tpeulen
    - mamba install -y boa
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    paths:
      - bld-dir/

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge:latest
  tags:
    - linux
  dependencies:
    - build:linux
    - build:windows
    - build:osx
  script:
    - source activate
    - mamba install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=main; else DEPLOY_LABEL=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_LABEL} -u ${CONDA_USER} --force bld-dir/**/*.tar.bz2

# Downstream projects
chisurf:
  stage: Trigger-cross-projects
  trigger: chisurf/chisurf

