stages:
- build
- test
- deploy
- Trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEPLOY_VARIABLE: "nightly"
  MINICONDA_VERSION: "latest"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /master/
      variables:
        DEPLOY_VARIABLE: "main"  # Override globally-defined DEPLOY_VARIABLE
    - when: always               # Run the pipeline in other cases

build:linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    - apt update -yq && apt -yq install build-essential
  script:
    - echo "I am the build stage."
    - source activate
    - conda install mamba boa conda-verify doxygen cmake -c conda-forge
    - |
      conda config --add channels salilab
      conda config --add channels tpeulen
    - conda deactivate # Make sure not in base env
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

deploy:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - echo "I am a deploy stage."
    - source activate
    - conda install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then ANACONDA_LABEL=main; else ANACONDA_LABEL=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${ANACONDA_LABEL} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2


# # Downstream projects
# chisurf:
#   stage: Trigger-cross-projects
#   trigger: tpeulen/chisurf

