stages:
  - build
  - test
  - deploy
  - Trigger-cross-projects

.build: &build
  stage: build
  artifacts:
    paths:
      - bld-dir/
.build_posix: &build_posix
  <<: *build
  script:
    - ./tools/build.sh
.build:lnx: &build_lnx
  <<: *build_posix
  before_script:
    - source "/opt/conda/etc/profile.d/conda.sh"
    - conda activate /opt/conda/
    - git submodule update --init --recursive --remote
build:lnx_x86:
  <<: *build_lnx
  image:
    name: condaforge/linux-anvil-cos7-x86_64
    entrypoint: [ "/bin/bash", "-i", "-c" ]
  tags:
    - x86_64
# build:lnx_ppc64le:
#   <<: *build_lnx
#   image:
#     name: condaforge/linux-anvil-ppc64le
#     entrypoint: [ "/bin/bash", "-i", "-c" ]
#   tags:
#     - ppc64le
# build:lnx_aarch64:
#   <<: *build_lnx
#   image:
#     name: condaforge/linux-anvil-aarch64
#     entrypoint: [ "/bin/bash", "-i", "-c" ]
#   tags:
#     - aarch64
build:osx:
  <<: *build_posix
  tags:
    - osx
  before_script:
    - git submodule update --init --recursive --remote
build:windows:
  <<: *build
  image: mambaforge:vs16
  tags:
    - win
  script:
    - cmd.exe
    - conda activate base
    - cd tools && git pull --force && cd..
    - .\tools\build.bat

test:linux:
  stage: test
  tags:
    - local
    - linux
  image: condaforge/mambaforge
  needs: ["build:lnx_x86"]
  before_script:
    - |
        export DEBIAN_FRONTEND=interactive
        export TZ=Europe/Berlin
        apt-get update -qy && apt-get install -qy git nfs-common # sshfs
  script:
    - |
        source activate base
        conda config --add channels tpeulen # for librttr
        conda config --add channels "file://`pwd`/bld-dir" # for chinet
        git clone --depth 1 https://gitlab.peulen.xyz/chisurf/chinet && cd chinet && git fetch && git switch $CI_COMMIT_REF_NAME
        mamba install python chinet nose scipy numba
        nosetests test

deploy:conda:
  stage: deploy
  image: condaforge/mambaforge
  tags:
    - x86_64
    - linux
  before_script:
    - git submodule update --init --recursive --remote
  script:
    - ./tools/deploy.sh

# Downstream projects
chisurf:
 stage: Trigger-cross-projects
 trigger: chisurf/chisurf

