stages:
- build
- test
- deploy
- Trigger-cross-projects

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build:linux:
  stage: build
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential doxygen
  script:
    - source activate
    - conda config --add channels tpeulen
    - mamba install boa conda-verify
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/


test:linux:
  stage: test
  tags:
    - linux
  image: condaforge/mambaforge:latest
  before_script:
    - apt update -yq && apt -yq install build-essential doxygen mongodb
  script:
    - source activate
    - conda config --add channels tpeulen
    - mamba install boa conda-verify
    - cd test && mkdir db && mongod --dbpath db &&
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

deploy:
  stage: deploy
  image: continuumio/miniconda3:latest
  tags:
    - linux
  dependencies:
    - build:linux
  script:
    - source activate
    - conda install anaconda-client
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then DEPLOY_LABEL=main; else DEPLOY_LABEL=nightly; fi
    - anaconda -t ${ANACONDA_API_TOKEN} upload -l ${DEPLOY_LABEL} -u ${CONDA_USER} --force bld-dir/linux-64/*.tar.bz2


# Downstream projects
chisurf:
  stage: Trigger-cross-projects
  trigger: chinet/chisurf

