language: generic
sudo: required

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - doxygen
    - os: osx
      osx_image: xcode9.4
      addons:
        homebrew:
          packages:
            - doxygen
          update: true

env:
  - BUILD_TARGET=3.7 MINICONDA_VERSION=latest

before_install:
  # export BRANCH environment variable to have unified names across different CI services
  - export BRANCH=$TRAVIS_BRANCH
  # Used to label the uploads
  - export CONDA_LABEL=$(if [ "TRAVIS_PULL_REQUEST_BRANCH" == "master" ]; then echo main; else echo nightly; fi)
  # Download and install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # setup conda to always accept commands
  - conda config --set always_yes yes --set changeps1 no
  # unlink homebrew's boost to interfere with conda boost
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
  # Add conda channels
  - conda config --add channels tpeulen
  - conda config --add channels salilab
  - conda update -q conda
  # Install conda packages necessary in the host to build the recipe
  - source activate base
  - conda install python=$BUILD_TARGET conda-build git
  # Make sure that the thirdparty gits are pulled
  - git submodule update --init --force
  # Build the recipe and add the build path to the channels
  - conda build conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  - conda install chinet -c "file://`pwd`/bld-dir"

script:
  # Install packages necessary to test the recipe
  - conda install python=$BUILD_TARGET mongodb nose coverage numba
  # Start the mongodb server (use conda mongodb as osx mongodb does not work)
  - sudo mkdir -p /data/db && sudo mongod &
  # create a link from nosetests to make sure that the correct nosetests is used
  - ln -sf $(which nosetests) $(pwd)/test/ && cd $(pwd)/test/
  # The nosetests keeps failing of osx (Illegal instruction: 4). This is likely
  # because the build machine are old. Hence, only test on Linux.
  # https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nosetests --with-coverage test_*.py; fi
  - cd ..

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - conda activate base
  # Install conda clinet to upload the package
  - conda install anaconda-client
  # Install codacy-coverage to upload the coverage results to codacy
  - pip install codacy-coverage
  # Process and upload the coverage results
  - coverage xml && python-codacy-coverage -r coverage.xml
  # Define labels for the conda package upload
  - if [[ "$BRANCH" == "master" ]]; then ANACONDA_LABEL=main; else ANACONDA_LABEL=nightly; fi
  # Upload the conda package
  - anaconda -t $ANACONDA_API_TOKEN upload -u $CONDA_USER -l $ANACONDA_LABEL bld-dir/$OS/*.tar.bz2 --force
  # Build the documentation
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      cd docs
      conda env create -f environment.yml
      conda activate docs_env
      make clean && make html
      # chinet.__version__ passed to PROJECT_NUMBER to have a single version number to manage.
      (cat Doxyfile ; echo "PROJECT_NUMBER=$(python -c 'from __future__ import print_function; import chinet; print(chinet.__version__)')" ) | doxygen -
      # Tell GitHub not to use jekyll to compile the docs
      touch _build/html/.nojekyll
      cd ..
      conda deactivate
    fi

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: development
    condition: $TRAVIS_OS_NAME = linux
  local_dir: docs/_build/html/

notifications:
  email:
    recipients:
      - thomas.otavio.peulen@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
