language: generic
sudo: required

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.4

env:
  # Build and test package on all supported python versions
  - BUILD_TARGET=3.7 MINICONDA_VERSION=latest
  # To make sure it's still working with conda 4.6
  # - BUILD_TARGET=3.7 MINICONDA_VERSION=4.6.14


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels tpeulen
  - conda config --add channels salilab
  - conda update -q conda
  - conda info -a
  - conda create -q -n build-environment python=$BUILD_TARGET conda-build anaconda-client jinja2 git mongodb
  - source activate build-environment
  - git submodule update --init --force
  - conda build conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  - conda install chinet -c "file://`pwd`/bld-dir"

script:
  # use nosetest. Some test use DB access. Hence, run a local MongoDB
  - sudo mkdir -p /data/db
  - sudo mongod &
  - conda install nose coverage numba
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  - echo $PWD
  - nosetests --with-coverage test_*.py
  - cd ..
  # Use Sphinx and doxygen to make the html docs
  - cd docs
  # matplotlib=2.2.3 because matplotlib.sphinxext was removed in matplotlib 3.x.x
  - conda config --add channels conda-forge
  - conda install -y sphinx_bootstrap_theme sphinx sphinx_rtd_theme numpydoc sphinx-autodoc-typehints matplotlib=2.2.3 sphinxcontrib-bibtex recommonmark numba doxygen
  # Use doxygen to build the C++ API documentation.
  # Here, the value in chinet.__version__ is passed to PROJECT_NUMBER in
  # so that there is only a single version number to manage.
  - make html
  - (cat Doxyfile ; echo "PROJECT_NUMBER=$(python -c 'from __future__ import print_function; import chinet; print(chinet.__version__)')" ) | doxygen -
  # Tell GitHub not to use jekyll to compile the docs
  - touch _build/html/.nojekyll
  - cd ..

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
#  - |
#    if [[ "$TRAVIS_BRANCH" == "master" ]];
#    then
#      anaconda upload bld-dir/**/chinet*.tar.bz2
#    fi

notifications:
  email:
    recipients:
      - thomas.otavio.peulen@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
