name: chinet

channels:
  - defaults
  - tpeulen
  - salilab

dependencies:
  - python=3.7
  - setuptools
  - cmake
  - eigen
  - nose
  - numpy
  - yaml
  - mongodb
  - swig 3.0.12.*
  - boost 1.67.0.*
  - intel-openmp
  - librttr 0.9.6.*
  - libmongoc 1.15.1.*
  - labellib
  - imp >=2.12.0
