CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx]
boost: 
  - 1.70.0
  - 1.71.0 # [py>27]
  - 1.72.0 # [py>27]
  - 1.73.0 # [py>27]
  - 1.74.0 # [py>27]
  - 1.75.0 # [py>27]
python:
  - 2.7
  - 3.7
  - 3.8
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  boost:
    max_pin: x.x.x
