boost: 
  # # Boost versions for py27
  # # are in conda-forge
  # - 1.60.0 # [py<=35]
  # - 1.61.0 # [py<=35]
  # - 1.62.0 # [py<=35]
  # - 1.63.0 # [py<=36]
  # - 1.64.0 # [py<=36]
  # - 1.65.0 # [py<=36]
  # - 1.65.1 # [py<=36]
  # - 1.66.0 # [py<=36]
  # - 1.67.0 # [py<=36]
  # - 1.68.0 # [py<=37]
  # - 1.69.0 # [py<=37]
  # Only build versions that
  # exist for py37 & py38 (as librttr)
  - 1.70.0 # [py<=38]
  - 1.71.0 # [py<=38]
  - 1.72.0 # [py>=36]
  - 1.73.0 # [py>=36]
  - 1.74.0 # [py>=36]
  - 1.75.0 # [py>=36]
python:
  # - 2.7
  - 3.7
  - 3.8
