CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx]
boost: 
  # # Boost versions for py27
  # # are in conda-forge
  # - 1.60.0
  # - 1.61.0
  # - 1.62.0
  # - 1.63.0
  # - 1.64.0
  # - 1.65.0
  # - 1.65.1
  # - 1.66.0
  # - 1.67.0
  # - 1.68.0
  # - 1.69.0
  # Only build versions that
  # exist for py37 & py38 (as librttr)
  - 1.70.0
  - 1.71.0
  - 1.72.0
  - 1.73.0
  #- 1.74.0 #py37 broken on osx
  - 1.75.0
python:
  # - 2.7
  - 3.7
  - 3.8
