{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:

  host:
    - python {{ python }}
    - numpy
    - setuptools
    - cmake
    - git
    - pathlib2 # [py27]
    - imp {{ imp }} # [win]
  build:
    - python {{ python }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    - numpy
    - swig
    - imp {{ imp }}
    - boost
    - numpy
    - librttr
    - eigen
    - llvm-openmp  # [osx]
    - libmongoc >=1.15.1
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('imp') }}
    - {{ pin_compatible('librttr') }}
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('libmongoc') }}
    - numpy
    - llvm-openmp  # [osx]

test:
  imports:
    - chinet

about:
  home: https://github.com/tpeulen/chinet
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
