{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  git_url: ..

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}boost{{ boost }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - doxygen
    - cmake
    - swig
    - python {{ python }}
    - boost-cpp {{ boost }}
    - libmongoc
    - librttr
    - numpy
  run:
    - python
    - boost-cpp
    - numpy
    - {{ pin_compatible('librttr') }}
    - {{ pin_compatible('libmongoc') }}
    - llvm-openmp  # [osx]

test:
  imports:
    - chinet
  #requires:
  #  - nose
  #  - python    
  #commands:
  #  # - mongodb # mongodb only on py37 -> use system mongodb
  #  # - cd test && mkdir db && mongod --dbpath db &&
  #  - nosetests

about:
  home: https://github.com/tpeulen/chinet
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
