{% set name = "chinet" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version|lower }}"

source:
  path: ..

build:
    number: 0
    #string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - cmake
    - swig<4.0.0
    - boost
    - eigen
    - openmp
    - setuptools
    - python {{ python }}
  host:
    - python {{ python }}
    - numpy
    - setuptools
    - librttr
    - libmongoc>=1.15.1
  run:
    - python {{ python }}
    - numpy
    - labellib

test:
  imports:
    - chinet

about:
  home: https://github.com/tpeulen/chinet
  license: MPL 2.0
  summary: Python bindings for chinet
  description: |
    chinet is a C++ library with Python wrapper to construct networks of
    computation node with associated ports that can be deposited in a
    mongoDB. Chinet is the data management backend of chisurf.
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
