{% set name = "chinet" %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "{{ name|lower }}"
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    #string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:

  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - imp 2.12.0.*
  build:
    - python {{ python }}
    - setuptools
    - {{ pin_compatible('numpy') }}
    - git
    - cmake
    - swig 3.0.12.*
    - intel-openmp
    - boost 1.67.0.*
    - librttr 0.9.6.*
    - libmongoc >=1.15.1
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - labellib
    - librttr 0.9.6.*
    - boost 1.67.0.* [win]
    - libboost 1.67.0.* [not win]
    - libmongoc >=1.15.1
    - imp 2.12.0.*

test:
  imports:
    - chinet

about:
  home: https://github.com/tpeulen/chinet
  license: Mozilla Public License 2.0 (MPL 2.0)
  summary: Python bindings for chinet
  description: |
    chinet is a C++ library with Python wrapper to construct networks of
    computation node with associated ports that can be deposited in a mongoDB.
    Chinet is the data management backend of chisurf.
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
