{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}

requirements:

  host:
    - python
    - numpy
    - imp {{ imp }} # [win]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  
    - python {{ python }}
    - setuptools
    - numpy
    - imp {{ imp }}
    - swig 3.0.12.*
    - cmake
    - doxygen
    - boost
    - eigen
    - llvm-openmp  # [osx]
    - librttr
    - libmongoc >=1.15.1
  run:
    - python {{ python }}
    - {{ pin_compatible('imp') }}
    - {{ pin_compatible('labellib') }}
    - {{ pin_compatible('librttr') }}
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('libmongoc') }}
    - numpy
    - llvm-openmp  # [osx]

test:
  imports:
    - chinet

about:
  home: https://github.com/tpeulen/chinet
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
