{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}

requirements:

  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    # patching IMP in setup.py therefore in host env
    - imp 2.13.0.* # [win]
  build:
    - python {{ python }}
    - setuptools
    - {{ pin_compatible('numpy') }}
    - git
    - cmake
    - imp 2.13.0.* # [not win]
    - swig 3.0.12.*
    - boost 1.67.0.* # [py < 38]
    - boost 1.71.0.* # [py >= 38]
    - llvm-openmp  # [osx]
    - librttr 0.9.6.*
    - libmongoc >=1.15.1
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - labellib
    - librttr 0.9.6.*
    - llvm-openmp  # [osx]
    - boost 1.67.0.* # [win]
    - libboost 1.71.0.* # [not win and py >= 38]
    - libboost 1.67.0.* # [not win and py < 38]
    - libmongoc >=1.15.1
    - imp 2.13.0.*

test:
  imports:
    - chinet

about:
  home: https://github.com/tpeulen/chinet
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://github.com/tpeulen.github.io/chinet/

extra:
  recipe-maintainers:
    - tpeulen
