IF(DEFINED ENV{CONDA_PREFIX})
    MESSAGE(STATUS "CONDA env seen: $ENV{CONDA_PREFIX}")
    FILE(TO_CMAKE_PATH "$ENV{CONDA_PREFIX}" CONDA_PATH)
    SET(CMAKE_PREFIX_PATH "${CONDA_PATH}")
    SET($ENV{PATH} "${CONDA_PATH}/bin;$ENV{PATH}")
    # Define python_command that is used to call python and locate the python libraries
    IF(MSVC)
        SET(CMAKE_MODULE_PATH "${CONDA_PATH}/Library/cmake;${CMAKE_MODULE_PATH}")
        INCLUDE_DIRECTORIES(${CONDA_PATH}/Library/include)
        LINK_DIRECTORIES(${CONDA_PATH}/Library/lib)
        FILE(TO_CMAKE_PATH ${CONDA_PATH}/bin/python.exe python_command)
    ELSE()
        SET(CMAKE_MODULE_PATH "${CONDA_PATH}/include/cmake;${CMAKE_MODULE_PATH}")
        INCLUDE_DIRECTORIES(${CONDA_PATH}/include)
        LINK_DIRECTORIES(${CONDA_PATH}/lib)
        FILE(TO_CMAKE_PATH ${CONDA_PATH}/bin/python python_command)
    ENDIF()
    MESSAGE(STATUS "CONDA PYTHON:" ${python_command})
    MESSAGE(STATUS "CMAKE_MODULE_PATH='${CMAKE_MODULE_PATH}'")
ELSE()
    MESSAGE(STATUS "No conda environment defined")
ENDIF()
