
name: Build and Upload Conda Packages

on:
  workflow_dispatch:
  release:
    types: ['released', 'prereleased']
  schedule:
    # At 11:00 AM, every 3 months
    - cron: "0 11 * */3 *"

jobs:
  build:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: |
          git submodule update --recursive --init --remote
          tools/install_macos_sdk.sh

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,tpeulen,defaults
          channel-priority: true

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Build and Upload Conda Package
        uses: aganders3/headless-gui@v1
        with:
          shell: bash -el {0}
          run: |
            mamba install conda-build boa anaconda-client
            cd conda-recipe
            # curl -sLO https://github.com/conda-forge/conda-forge-pinning-feedstock/raw/main/recipe/conda_build_config.yaml
            conda mambabuild . --output-folder conda-bld -c tpeulen
            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2
